<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class UniversityBooksSeeder extends Seeder
{
    /**
     * Run the database seeds for University E-Library.
     */
    public function run(): void
    {
        // 1. Ensure University Categories / Faculties exist
        $categoriesData = [
            [
                'name' => 'បច្ចេកវិទ្យា និងវិទ្យាសាស្ត្រកុំព្យូទ័រ',
                'slug' => 'technology',
                'icon' => 'code',
                'description' => 'Software Engineering, Computer Science, Cybersecurity, AI, Cloud & Data Science',
            ],
            [
                'name' => 'ពាណិជ្ជកម្ម និងការគ្រប់គ្រង',
                'slug' => 'business-management',
                'icon' => 'briefcase',
                'description' => 'Business Administration, Marketing, Management, Entrepreneurship & Leadership',
            ],
            [
                'name' => 'សេដ្ឋកិច្ច និងហិរញ្ញវត្ថុ',
                'slug' => 'economics-finance',
                'icon' => 'chart-bar',
                'description' => 'Economics, Accounting, Banking, Corporate Finance & Investment',
            ],
            [
                'name' => 'វិស្វកម្ម និងស្ថាបត្យកម្ម',
                'slug' => 'engineering',
                'icon' => 'sparkles',
                'description' => 'Civil Engineering, Electrical Engineering, Architecture & Construction',
            ],
            [
                'name' => 'នីតិសាស្ត្រ និងវិទ្យាសាស្ត្រនយោបាយ',
                'slug' => 'law',
                'icon' => 'landmark',
                'description' => 'Civil Law, Criminal Law, Commercial Law, Constitutional Law & International Relations',
            ],
            [
                'name' => 'ភាសាបរទេស និងទំនាក់ទំនង',
                'slug' => 'languages',
                'icon' => 'translate',
                'description' => 'Academic English, Business Communication, Chinese, French & Translation',
            ],
            [
                'name' => 'ស្នាដៃស្រាវជ្រាវ និងសារណាបញ្ចប់ការសិក្សា',
                'slug' => 'general-works',
                'icon' => 'book-open',
                'description' => 'Research Methodology, Academic Writing, Capstone Theses & Journal Papers',
            ],
            [
                'name' => 'វិទ្យាសាស្ត្រ និងគណិតវិទ្យាឧត្តមសិក្សា',
                'slug' => 'science-math',
                'icon' => 'atom',
                'description' => 'Calculus, Linear Algebra, Statistics, Applied Physics & Mathematics',
            ],
            [
                'name' => 'ប្រវត្តិសាស្ត្រ វប្បធម៌ និងទស្សនវិជ្ជា',
                'slug' => 'geography-history',
                'icon' => 'globe',
                'description' => 'Cambodian History, Southeast Asian Civilizations, Philosophy & Ethics',
            ],
        ];

        $categoriesMap = [];
        foreach ($categoriesData as $c) {
            $cat = Category::updateOrCreate(
                ['slug' => $c['slug']],
                [
                    'name' => $c['name'],
                    'icon' => $c['icon'],
                    'description' => $c['description'],
                ]
            );
            $categoriesMap[$c['slug']] = $cat;
        }

        // 2. Clean up old non-university K-12 primary / secondary school books
        $k12Titles = [
            'ស្តង់ដាសាលាបឋមសិក្សា',
            'ស្តង់ដាសាលាបឋមសិក្សា​គំរូ',
            'ស្តង់ដាសាលាមធ្យមសិក្សា',
            'សេចក្តីណែនាំអនុវត្តការធ្វើតេស្តស្តង់ដាកម្រិតសាលារៀន',
            'ការអភិវឌ្ឍកុមារឲ្យរភ្ជាប់នឹងការអប់រំបឋមសិក្សា ថ្នាក់ទី១_៣',
        ];
        Book::whereIn('title', $k12Titles)->delete();

        // 3. University Academic Books Dataset
        $techId = $categoriesMap['technology']->id;
        $bizId = $categoriesMap['business-management']->id;
        $econId = $categoriesMap['economics-finance']->id;
        $engId = $categoriesMap['engineering']->id;
        $lawId = $categoriesMap['law']->id;
        $langId = $categoriesMap['languages']->id;
        $genId = $categoriesMap['general-works']->id;
        $sciId = $categoriesMap['science-math']->id;
        $histId = $categoriesMap['geography-history']->id;

        $universityBooks = [
            // ==========================================
            // 1. SOFTWARE ENGINEERING & COMPUTER SCIENCE
            // ==========================================
            [
                'title' => 'Software Engineering: A Practitioner\'s Approach (9th Edition)',
                'author' => 'Roger S. Pressman, Bruce R. Maxim',
                'isbn' => '978-1259872976',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'Software Engineering',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 10,
                'available_copies' => 8,
                'location_shelf' => 'Shelf CS-01',
                'published_year' => 2020,
                'description' => 'The comprehensive university textbook on software engineering lifecycle, agile methods, architectural design, testing, and capstone project execution for graduating seniors.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Designing Data-Intensive Applications: The Big Ideas Behind Reliable Systems',
                'author' => 'Martin Kleppmann',
                'isbn' => '978-1449373320',
                'category_id' => $techId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'Software Engineering',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 8,
                'available_copies' => 5,
                'location_shelf' => 'Shelf CS-02',
                'published_year' => 2017,
                'description' => 'The definitive guide for senior software engineers on data storage, distributed systems, replication, partitioning, transactions, and stream processing.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Design Patterns: Elements of Reusable Object-Oriented Software',
                'author' => 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides (GoF)',
                'isbn' => '978-0201633610',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'Software Engineering',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 12,
                'available_copies' => 9,
                'location_shelf' => 'Shelf CS-03',
                'published_year' => 2019,
                'description' => 'Classic architectural patterns (Creational, Structural, Behavioral) essential for university graduation projects and enterprise software development.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'author' => 'Robert C. Martin',
                'isbn' => '978-0132350884',
                'category_id' => $techId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'Software Engineering',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 15,
                'available_copies' => 11,
                'location_shelf' => 'Shelf CS-04',
                'published_year' => 2008,
                'description' => 'Fundamental principles of professional code architecture, readability, refactoring, unit testing, and maintainable software construction.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Introduction to Algorithms (4th Edition)',
                'author' => 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein (CLRS)',
                'isbn' => '978-0262046305',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិទ្យាសាស្ត្រកុំព្យូទ័រ',
                'grade' => 'ឆ្នាំទី ២',
                'target_academic_year' => 2,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 14,
                'available_copies' => 10,
                'location_shelf' => 'Shelf CS-05',
                'published_year' => 2022,
                'description' => 'The globally standard university textbook on data structures, divide-and-conquer, dynamic programming, greedy algorithms, and graph theory.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Database System Concepts (7th Edition)',
                'author' => 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan',
                'isbn' => '978-0078022159',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិទ្យាសាស្ត្រកុំព្យូទ័រ',
                'grade' => 'ឆ្នាំទី ២',
                'target_academic_year' => 2,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 12,
                'available_copies' => 8,
                'location_shelf' => 'Shelf CS-06',
                'published_year' => 2019,
                'description' => 'Relational database architecture, SQL, relational calculus, query optimization, concurrency control, indexing, and NoSQL databases.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => false,
            ],

            // ==========================================
            // 2. CYBERSECURITY & NETWORK
            // ==========================================
            [
                'title' => 'The Web Application Hacker\'s Handbook: Finding and Exploiting Security Flaws',
                'author' => 'Dafydd Stuttard, Marcus Pinto',
                'isbn' => '978-1118026472',
                'category_id' => $techId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'សន្តិសុខសាយប័រ',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Cybersecurity (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 7,
                'available_copies' => 5,
                'location_shelf' => 'Shelf SEC-01',
                'published_year' => 2021,
                'description' => 'Advanced penetration testing, OWASP Top 10 vulnerabilities, authentication bypass, SQL injection, and defensive coding for university cybersecurity students.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Computer Networking: A Top-Down Approach (8th Edition)',
                'author' => 'James Kurose, Keith Ross',
                'isbn' => '978-0136681557',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'បណ្តាញកុំព្យូទ័រ',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'Network Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 11,
                'available_copies' => 7,
                'location_shelf' => 'Shelf NET-01',
                'published_year' => 2021,
                'description' => 'Top-down approach to Internet protocols, application layer, TCP/UDP transport, IP routing, SDN, and network security architectures.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],

            // ==========================================
            // 3. ARTIFICIAL INTELLIGENCE & DATA SCIENCE
            // ==========================================
            [
                'title' => 'Artificial Intelligence: A Modern Approach (4th Edition)',
                'author' => 'Stuart Russell, Peter Norvig',
                'isbn' => '978-0134610993',
                'category_id' => $techId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'បញ្ញាសិប្បនិម្មិត (AI)',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Artificial Intelligence (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 9,
                'available_copies' => 6,
                'location_shelf' => 'Shelf AI-01',
                'published_year' => 2020,
                'description' => 'The leading authority on artificial intelligence: intelligent agents, search algorithms, logic, probabilistic reasoning, machine learning, and deep learning.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Python Data Science Handbook: Essential Tools for Working with Data',
                'author' => 'Jake VanderPlas',
                'isbn' => '978-1491912058',
                'category_id' => $techId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិទ្យាសាស្ត្រទិន្នន័យ',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'Data Science (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 10,
                'available_copies' => 8,
                'location_shelf' => 'Shelf DS-01',
                'published_year' => 2022,
                'description' => 'Comprehensive guide to IPython, NumPy, Pandas, Matplotlib, and Scikit-Learn for university data science analysis.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => false,
            ],

            // ==========================================
            // 4. BUSINESS ADMINISTRATION & MARKETING
            // ==========================================
            [
                'title' => 'Strategic Management: Concepts and Cases (17th Edition)',
                'author' => 'Fred R. David, Forest R. David',
                'isbn' => '978-0135199978',
                'category_id' => $bizId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'គ្រប់គ្រងពាណិជ្ជកម្ម',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'General Management (គ្រប់គ្រង)',
                'cover_image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 12,
                'available_copies' => 9,
                'location_shelf' => 'Shelf BM-01',
                'published_year' => 2020,
                'description' => 'Senior university capstone text covering vision/mission, external/internal audit, strategy formulation, SWOT, BCG matrix, and competitive strategy implementation.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Marketing Management (16th Global Edition)',
                'author' => 'Philip Kotler, Kevin Lane Keller, Alexander Chernev',
                'isbn' => '978-0135887158',
                'category_id' => $bizId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ទីផ្សារ (Marketing)',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Marketing (គ្រប់គ្រង)',
                'cover_image' => 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 14,
                'available_copies' => 10,
                'location_shelf' => 'Shelf MKT-01',
                'published_year' => 2021,
                'description' => 'The world\'s foremost marketing text: digital marketing transformation, consumer behavior analysis, brand positioning, omnichannel management, and global metrics.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Zero to One: Notes on Startups, or How to Build the Future',
                'author' => 'Peter Thiel, Blake Masters',
                'isbn' => '978-0804139298',
                'category_id' => $bizId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ភាពជាសហគ្រិន',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'General Management (គ្រប់គ្រង)',
                'cover_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 8,
                'available_copies' => 4,
                'location_shelf' => 'Shelf BM-02',
                'published_year' => 2014,
                'description' => 'Innovation and startup strategy: how university graduates and entrepreneurs move from zero to one by building creative monopolies.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'The Lean Startup: How Constant Innovation Creates Radically Successful Businesses',
                'author' => 'Eric Ries',
                'isbn' => '978-0307887894',
                'category_id' => $bizId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ភាពជាសហគ្រិន',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'International Business (គ្រប់គ្រង)',
                'cover_image' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 10,
                'available_copies' => 6,
                'location_shelf' => 'Shelf BM-03',
                'published_year' => 2011,
                'description' => 'Validated learning, Minimum Viable Product (MVP), Build-Measure-Learn feedback loops, and agility in enterprise launch.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => false,
            ],

            // ==========================================
            // 5. ACCOUNTING, FINANCE & ECONOMICS
            // ==========================================
            [
                'title' => 'Financial Accounting and Reporting (20th Edition)',
                'author' => 'Barry Elliott, Jamie Elliott',
                'isbn' => '978-1292399928',
                'category_id' => $econId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'គណនេយ្យ',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'Accounting (សេដ្ឋកិច្ច)',
                'cover_image' => 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 12,
                'available_copies' => 9,
                'location_shelf' => 'Shelf ACC-01',
                'published_year' => 2022,
                'description' => 'Comprehensive textbook on IFRS standards, balance sheet recognition, cash flows, consolidated financial statements, and auditing basics.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Corporate Finance (5th Global Edition)',
                'author' => 'Jonathan Berk, Peter DeMarzo',
                'isbn' => '978-1292304151',
                'category_id' => $econId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ហិរញ្ញវត្ថុ',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Banking & Finance (សេដ្ឋកិច្ច)',
                'cover_image' => 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 11,
                'available_copies' => 8,
                'location_shelf' => 'Shelf FIN-01',
                'published_year' => 2020,
                'description' => 'Capital budgeting, cost of capital, valuation models, capital structure, dividend policy, derivatives, and risk management for graduating finance seniors.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Principles of Economics (9th Edition)',
                'author' => 'N. Gregory Mankiw',
                'isbn' => '978-0357038314',
                'category_id' => $econId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'សេដ្ឋកិច្ចវិទ្យា',
                'grade' => 'ឆ្នាំទី ១',
                'target_academic_year' => 1,
                'recommended_major' => 'Economics (សេដ្ឋកិច្ច)',
                'cover_image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 18,
                'available_copies' => 14,
                'location_shelf' => 'Shelf ECO-01',
                'published_year' => 2020,
                'description' => 'The premier introduction to microeconomics and macroeconomics: market supply and demand, elasticity, monetary and fiscal policy, and international trade.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],

            // ==========================================
            // 6. CIVIL & ELECTRICAL ENGINEERING
            // ==========================================
            [
                'title' => 'Structural Analysis (10th Edition in SI Units)',
                'author' => 'R. C. Hibbeler',
                'isbn' => '978-1292247137',
                'category_id' => $engId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិស្វកម្មសំណង់ស៊ីវិល',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Civil Engineering (វិស្វកម្ម)',
                'cover_image' => 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 10,
                'available_copies' => 7,
                'location_shelf' => 'Shelf ENG-01',
                'published_year' => 2020,
                'description' => 'Analysis of statically determinate and indeterminate beams, trusses, and rigid frames using classical displacement and force methods for senior civil engineers.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Design of Reinforced Concrete (10th Edition)',
                'author' => 'Jack C. McCormac, Russell H. Brown',
                'isbn' => '978-1118879108',
                'category_id' => $engId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិស្វកម្មសំណង់ស៊ីវិល',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Civil Engineering (វិស្វកម្ម)',
                'cover_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 9,
                'available_copies' => 6,
                'location_shelf' => 'Shelf ENG-02',
                'published_year' => 2021,
                'description' => 'Theory and design of reinforced concrete structural elements: beams, columns, slabs, footings, and retaining walls according to ACI Code.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Electrical Engineering: Principles and Applications (7th Edition)',
                'author' => 'Allan R. Hambley',
                'isbn' => '978-0134484143',
                'category_id' => $engId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិស្វកម្មអគ្គិសនី',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'Electrical Engineering (វិស្វកម្ម)',
                'cover_image' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 8,
                'available_copies' => 5,
                'location_shelf' => 'Shelf ELEC-01',
                'published_year' => 2018,
                'description' => 'Core concepts of DC/AC circuits, transient response, diodes, transistors, operational amplifiers, and digital logic circuits for university engineering majors.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => false,
            ],

            // ==========================================
            // 7. CAMBODIAN LAW & LEGAL STUDIES
            // ==========================================
            [
                'title' => 'ក្រមរដ្ឋប្បវេណី និងនីតិវិធីរដ្ឋប្បវេណីកម្ពុជា (ការបកស្រាយ និងការអនុវត្ត)',
                'author' => 'គណៈមេធាវីនៃព្រះរាជាណាចក្រកម្ពុជា',
                'isbn' => '978-99950-88-01-2',
                'category_id' => $lawId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'នីតិសាស្ត្រ',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'នីតិសាស្ត្រ (Law)',
                'cover_image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 15,
                'available_copies' => 11,
                'location_shelf' => 'Shelf LAW-01',
                'published_year' => 2022,
                'description' => 'ឯកសារយោង និងសៀវភៅសិក្សាគោលស្តីពីក្រមរដ្ឋប្បវេណី បុគ្គល សិទ្ធិលើទ្រព្យសម្បត្តិ កាតព្វកិច្ច កិច្ចសន្យា និងនីតិវិធីតុលាការរដ្ឋប្បវេណីកម្រិតឧត្តមសិក្សា។',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'ក្រមព្រហ្មទណ្ឌ និងនីតិវិធីព្រហ្មទណ្ឌនៃព្រះរាជាណាចក្រកម្ពុជា',
                'author' => 'ក្រសួងយុត្តិធម៌ និងសាកលវិទ្យាល័យភូមិន្ទនីតិសាស្ត្រ',
                'isbn' => '978-99950-88-02-9',
                'category_id' => $lawId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'នីតិសាស្ត្រ',
                'grade' => 'ឆ្នាំទី ៣',
                'target_academic_year' => 3,
                'recommended_major' => 'នីតិសាស្ត្រ (Law)',
                'cover_image' => 'https://images.unsplash.com/photo-1453733197783-feed44ce0253?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 14,
                'available_copies' => 10,
                'location_shelf' => 'Shelf LAW-02',
                'published_year' => 2023,
                'description' => 'គោលការណ៍ច្បាប់ព្រហ្មទណ្ឌ ទោសានុទោស ការស៊ើបអង្កេត ការចោទប្រកាន់ និងនីតិវិធីជំនុំជម្រះក្តីនៅតុលាការកម្ពុជា។',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],

            // ==========================================
            // 8. RESEARCH METHODOLOGY & THESIS WRITING
            // ==========================================
            [
                'title' => 'វិធីសាស្ត្រស្រាវជ្រាវបែបវិទ្យាសាស្ត្រ សម្រាប់ការសរសេរសារណាបញ្ចប់ការសិក្សា',
                'author' => 'បណ្ឌិតសភាបណ្ឌិត និងអ្នកស្រាវជ្រាវឧត្តមសិក្សា',
                'isbn' => '978-99950-99-01-8',
                'category_id' => $genId,
                'subcategory' => 'សារណាស្រាវជ្រាវ',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'វិធីសាស្ត្រស្រាវជ្រាវ',
                'grade' => 'ឆ្នាំទី ៤',
                'target_academic_year' => 4,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 20,
                'available_copies' => 16,
                'location_shelf' => 'Shelf RS-01',
                'published_year' => 2023,
                'description' => 'សៀវភៅណែនាំស្តង់ដារសម្រាប់និស្សិតឆ្នាំទី៤ ក្នុងការរៀបចំសំណើសុំស្រាវជ្រាវ ការប្រមូលទិន្នន័យ ការវិភាគបែបបរិមាណ និងគុណភាព និងការសរសេរសារណាបញ្ចប់ការសិក្សា។',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Academic Writing and Critical Thinking for University Students',
                'author' => 'Stephen Bailey',
                'isbn' => '978-1138048744',
                'category_id' => $langId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ភាសាអង់គ្លេស',
                'grade' => 'ឆ្នាំទី ១',
                'target_academic_year' => 1,
                'recommended_major' => 'English Literature (ភាសាបរទេស)',
                'cover_image' => 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 15,
                'available_copies' => 12,
                'location_shelf' => 'Shelf ENG-01',
                'published_year' => 2021,
                'description' => 'Essential guide for undergraduate students on constructing academic arguments, literature reviews, citations (APA, Harvard), and scholarly prose.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'A History of Cambodia (4th Edition)',
                'author' => 'David P. Chandler',
                'isbn' => '978-0813343631',
                'category_id' => $histId,
                'subcategory' => 'ឯកសារយោង',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'ប្រវត្តិវិទ្យា',
                'grade' => 'ឆ្នាំទី ១',
                'target_academic_year' => 1,
                'recommended_major' => 'ទូទៅ (General)',
                'cover_image' => 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 12,
                'available_copies' => 9,
                'location_shelf' => 'Shelf HC-01',
                'published_year' => 2008,
                'description' => 'Authoritative university reference on Cambodian civilization, Angkorian era, colonial period, and modern political history.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => true,
            ],
            [
                'title' => 'Calculus: Early Transcendentals (9th Edition)',
                'author' => 'James Stewart, Daniel Clegg, Saleem Watson',
                'isbn' => '978-1337613927',
                'category_id' => $sciId,
                'subcategory' => 'សៀវភៅគោល',
                'education_level' => 'បរិញ្ញាបត្រ',
                'subject' => 'គណិតវិទ្យាឧត្តមសិក្សា',
                'grade' => 'ឆ្នាំទី ១',
                'target_academic_year' => 1,
                'recommended_major' => 'Software Engineering (វិទ្យាសាស្ត្រកុំព្យូទ័រ)',
                'cover_image' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&auto=format&fit=crop&q=80',
                'total_copies' => 16,
                'available_copies' => 12,
                'location_shelf' => 'Shelf MATH-01',
                'published_year' => 2020,
                'description' => 'The world-standard undergraduate calculus textbook: limits, derivatives, integrals, multivariable calculus, and vector analysis for STEM students.',
                'views_count' => 0,
                'downloads_count' => 0,
                'is_featured' => false,
            ],
        ];

        foreach ($universityBooks as $b) {
            Book::updateOrCreate(
                ['isbn' => $b['isbn']],
                $b
            );
        }
    }
}
